#
# Warning: this template isn't fully  functioning, it's just for experiemting with CloudFormation
# You'll need to tune it manually if you'd like to use it.
#
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Gallery lambda 2 for resizing the pictures
Resources:
  galleryResizeLambda2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.aimplicits.gallery.ResizerLambda
      Runtime: java8
      CodeUri: ./target/scala-2.12/gallery_resizer_lambda-assembly-0.1-SNAPSHOT.jar
      Description: Gallery lambda 2 for resizing the pictures
      MemorySize: 512
      Timeout: 15
      Role: 'arn:aws:iam::438406322161:role/gallery_lambda_role'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: '/gallery/resized/{filePath+}'
            Method: GET
      Environment:
        Variables:
          galleryFolder: sampleFolder
          galleryBucket: sampleBucket
      Tags:
        gallery: 'automated'
